# language: ruby
checks:
    ruby:
        style_guard_clause:
            min_body_length: '1'
        style_global_vars: true
        style_file_name: true
        style_flip_flop: true
        style_even_odd: true
        style_end_of_line: true
        style_encoding:
            enforced_style: always
        style_empty_literal: true
        style_each_with_object: true
        style_deprecated_hash_methods: true
        style_constant_name: true
        style_class_vars: true
        style_class_methods: true
        style_class_check:
            enforced_style: 'is_a?'
        style_class_and_module_camel_case: true
        style_character_literal: true
        style_auto_resource_cleanup: true
        style_attr: true
        style_ascii_identifiers: true
        style_ascii_comments: true
        style_array_join: true
        style_and_or: true
        style_alias: true
        style_accessor_method_name: true
        smell_line_length:
            max: '120'
        smell_block_nesting:
            max: '3'
        rails_validation: true
        rails_timezone: true
        rails_scope_args: true
        rails_read_write_attribute: true
        rails_output: true
        rails_has_and_belongs_to_many: true
        rails_foreach: true
        rails_find_by: true
        rails_delegate: true
        rails_date: false
        performance_size: true
        performance_sample: true
        performance_reverse_each: true
        performance_flatmap: true
        performance_detect: true
        performance_count: true
        lint_void: true
        lint_useless_setter_call: true
        lint_useless_else_without_rescue: true
        lint_useless_comparison: true
        lint_useless_assignment: true
        lint_useless_access_modifier: true
        lint_unused_method_argument: true
        lint_unused_block_argument: true
        lint_unreachable_code: true
        lint_underscore_prefixed_variable_name: true
        lint_shadowing_outer_local_variable: true
        lint_require_parentheses: true
        lint_non_local_exit_from_iterator: true
        lint_literal_in_interpolation: true
        lint_literal_in_condition: true
        lint_handle_exceptions: true
        lint_eval: true
        lint_ensure_return: true
        lint_empty_interpolation: true
        lint_empty_ensure: true
        lint_each_with_object_argument: true
        lint_duplicate_methods: true
        lint_deprecated_class_methods: true
        lint_debugger: true
        lint_assignment_in_condition:
            allow_safe_assignment: true
        lint_ambiguous_regexp_literal: true
        lint_ambiguous_operator: true
        duplicate_code: true
        code_rating: true

build:
    tests:
        override:
            -
                command: 'bundle exec rake test'
                environment:
                    'SCRUTINIZER_CC_FILE': 'my-coverage'
                coverage:
                    file: 'my-coverage'
                    format: 'rb-cc'
